### PR TITLE
synch codesandbox template with github-master

### PR DESCRIPTION
**Pull request by suren-atoyan**

### CODE REVIEW

**Review by Trade-Help — APPROVED** [review]
I wanted to upgrade this to MUI 5 for my own use and thought I would share the changes back. While I was at it, I updated all packages to their latest version and made necessary changes in the app. Finally, I had the need for a bottom navigation section when on mobile, so it is included in this also.

This is my first time ever contributing to someone else's code, so please review and let me know if there is anything that needs to be updated.

Thanks!

**Comment by Trade-Help** [comment]
README.md

**Comment by Trade-Help** [comment]
> README.md

**Comment by suren-atoyan** [comment]
hey, @Trade-Help v2 is released 🎉 which includes MUI v5. Please check the master branch 🙂

**Pull request closed without merging**
